### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by festivities** [Shichiha/bark-engin#2]
how to use this? i can't get it to work... can i use this for ps in genshin impact? i heard you have 3.0 devkit can you give it plss? thx

**Comment by Shichiha** [comment]
clone repo, `npm i`, `npm run build`, open `dist/index.html`  
here is a preview of the index.html 🥺
[preview](https://crepe.moe/YRnztrpr)

controls: up down

if that doesnt work just go to https://jsfiddle.net/permadq5/1/ and test there tbh

**Comment by Shichiha** [comment]
oh i forgot to say, the main branch is still outdated and im using the `3d` branch for development
(no, you cannot use this for ps alone, you can to some degree... but nobody would.)
(also no, i do not have the devkit...)

edit: `3d` branch has been merged to `main`

**Comment by Shichiha** [comment]
> (no, you cannot use this for ps alone, you can to some degree... but nobody would.)

scratch that im rendering `spawns.json`
